name: Build project with Maven
on:
  pull_request: 
  push:
    branches-ignore: [ master ]
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@e9512a931da86017e9d4d564a24616d8444d2193 # pin@v2
    - name: Java setup
      uses: actions/setup-java@32b40ff017548e5bb9853df55204c675fa287265 # pin@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@99d99cd262b87f5f8671407a1e5c1ddfa36ad5ba # pin@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      run: mvn -B clean install com.mycila:license-maven-plugin:check
